<template>
    <div>
        switchdemo
        <p>switch内容</p>
        <p>switch内容</p>
        <p>switch内容</p>
        <p>switch内容</p>
        <p>switch内容</p>
        <p>switch内容</p>
        <p>switch内容</p>
        <p>switch内容</p>
        <p>switch内容</p>
        <p>switch内容</p>
        <p>switch内容</p>
        <p>switch内容</p>
        <p>switch内容</p>
        <p>switch内容</p>
        <p>switch内容</p>
        <p>switch内容</p>
        <p>switch内容</p>
        <p>switch内容</p>
        <p>switch内容</p>
        <p>switch内容</p>
        <p>switch内容</p>
        <p>switch内容</p>
        <p>switch内容</p>
        <p>switch内容</p>
        <p>switch内容</p>
        <p>switch内容</p>
        <p>switch内容</p>
        <p>switch内容</p>
        <p>switch内容</p>
        <p>switch内容</p>
        <p>switch内容</p>
        <p>switch内容</p>
        <p>switch内容</p>
        <p>switch内容</p>
        <p>switch内容</p>
        <p>switch内容</p>
        <p>switch内容</p>
        <p>switch内容</p>
        <p>switch内容</p>
        <p>switch内容</p>
        <p>switch内容</p>
        <p>switch内容</p>
        <p>switch内容</p>
        <p>switch内容</p>
        <p>switch内容</p>
        <p>switch内容</p>
        <p>switch内容</p>
        <p>switch内容</p>
        <p>switch内容</p>
        <p>switch内容</p>
        <p>switch内容</p>
        <p>switch内容</p>
        <p>switch内容</p>
        <p>switch内容</p>
        <p>switch内容</p>
        <p>switch内容</p>
        <p>switch内容</p>
        <p>switch内容</p>
    </div>
</template>